baseURL = "https://sdesojo.github.io/sdesojo/"
title = "/sdesojo"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Silvia de Sojo Caso"]
    notebook = "https://www.linkedin.com/in/silvia-de-sojo-caso-281655b8/"
    data = "https://findit.dtu.dk/en/catalog/6251698841bfc310d66878ff"
    github = "https://github.com/sdesojo"
    [[params.nav]]
        label = "Research"
        link = "/research"
    [[params.nav]]
        label = "CV"
        link = "/cv"
    [[params.nav]]
        label = "Contact"
        link = "/contact"

